### ISSUE TITLE
[PE-D][Tester D] Application accepts unrealistically long phone numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#181]
Steps to Reproduce:

Add a person with an excessively long phone number using the command add n/Johnvdsvsvs Doe p/9876236832468237468274682746827468327547354444444444443274725472357475432 e/johnd@example.com m/CS2103 f/Computing v/311, Clementi Ave 2, #02-25 t/friends t/owesMoney a/mon 12:00 14:00 a/thur 12:00 14:00.

Expected: The application should validate phone numbers and restrict them to a realistic length.

Actual: The application allows for a phone number that is far beyond normal length without any error or warning.

![photo_2024-04-05 16.45.23.jpeg](https://raw.githubusercontent.com/Shauryan123/ped/main/files/f700ae41-37a4-4074-8aad-8c81cd1ece23.jpeg)

Suggestion: Implementing a reasonable character limit for phone numbers would ensure data integrity and prevent potential errors during usage.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Shauryan123/ped#4

**Comment by iynixil** [comment]
According to [CS2103 website](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#2-start-fixing-ped-bugs-before-the-tutorial:~:text=This%20is%20not%20considered%20%27incorrect%27%20(giving%20more%20freedom%20to%20the%20user%20is%20not%20necessarily%20incorrect)), giving more freedom in the user input is not necessarily incorrect.
However, real-life applications do have many verification for real-life values and this could be a possible enhancement.

Fix:
- Mention explicitly in UG about valid values for phone numbers.
