### ISSUE TITLE
[PE-D][Tester E] find/filter Command limitations: email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-3/tp#186]
![image.png](https://raw.githubusercontent.com/legionlegion/ped/main/files/c4054ae9-6fde-4605-8cf2-884811fb4200.png)

The `find` and `filter` command in the current version does not support searching by email address which is an oversight that diminishes its utility for users who rely on email as a key identifier.
This absence forces users to use less efficient methods for locating specific entries, leading to increased search times and potential frustration. As email search is a standard feature in similar data retrieval tools, its absence in the find command signifies a notable deficiency in the product design, making the feature incomplete for practical usage.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: legionlegion/ped#2

**Comment by iynixil** [comment]
This is a valid point raised.
Will consider in future implementations to enhance the `find`/`filter` command for `email` attribute.

No fix; mentioned under `filter` and `find` commands that only specific attributes work.
