### ISSUE TITLE
[PE-D][Tester E] fav & unfav resets the view to default

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#205]
![image.png](https://raw.githubusercontent.com/legionlegion/ped/main/files/1240d687-6656-4b73-a82a-afb0e6d67d75.png)

After `find james`, when I mark the 1s person in the list as favourite using `fav 1`, the list resets to the default view, as seen below:

![image.png](https://raw.githubusercontent.com/legionlegion/ped/main/files/6957f5db-ddad-409b-9423-dea5661ec100.png)

Not a severe problem, but this behaviour is not explictly specified in the user guide.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: legionlegion/ped#4

**Comment by tsulim** [comment]
This is valid and can be amended. 👍
