### ISSUE TITLE
[PE-D][Tester E] meeting-delete missing examples section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#212]
![image.png](https://raw.githubusercontent.com/legionlegion/ped/main/files/fe55d337-3294-42cc-9aca-a96ca7def433.png)

Example commands have been provided for all other modification commands, but `meeting-delete` is missing this section.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: legionlegion/ped#11

**Comment by Pluiexo** [comment]
Fix: Fix UG as `meeting-delete` examples are there but not headed and spaced  properly
