### ISSUE TITLE
[PE-D][Tester E] Inconsistency in Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#218]
![image.png](https://raw.githubusercontent.com/legionlegion/ped/main/files/7b846f0b-4a45-42ae-a518-239ad89ad3d6.png)

To standardise your commands, the e.g. for `refresh` can be removed to match other 1-word commands that do not need any other parameters.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: legionlegion/ped#14

**Comment by Pluiexo** [comment]
I think it was not mentioned, but the `refresh` can be reordered to the bottom below help for better visibility
