### ISSUE TITLE
[PE-D][Tester D] Sorting by attribute feature documentation not consistent with the other features

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#226]
![Screenshot 2024-04-06 at 12.12.08 AM.png](https://raw.githubusercontent.com/Shauryan123/ped/main/files/b82c85cd-ed36-4e52-b7f2-c773c6961668.png)

All other features have 2 examples whereas sorting by attribute has 3 examples.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Shauryan123/ped#12

**Comment by whitesnowx** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 

<details>
<summary> Added Examples</summary>

```
add n/Chihiro Ogino m/GEC1024 e/spirited@example.com f/FASS v/The Spirit Realm p/20122001 a/tues 21:00 22:00 a/wednesday 00:00 23:59
```
```
edit 3 m/GEA1000
```
```
filter f/Computing t/professor
```
```
find li
```
```
meeting-add 1 d/CS2100 Consultation s/11/06/2024 08:00
```


<details>

##### Pending test checks
