### ISSUE TITLE
Update Module Validity and error message

### ISSUE THREAD

**Issue by whitesnowx** [AY2324S2-CS2103-F08-3/tp#235]
* Error Message for valid modules (accept capital letters)
* Modules found to be have 2 suffix: `ASP1201CH`

##### _Based on this, should be allowed to fix in 1.4_
![image](https://github.com/AY2324S2-CS2103-F08-3/tp/assets/68015911/acdc02bd-4765-4e0a-96f6-7a5382fcfba8)

**Comment by Pluiexo** [comment]
👍  , Though ensure that your fix has minimal changes to the codebase
