### ISSUE TITLE
Implement Sort functionality for contacts

### ISSUE THREAD

**Issue by tsulim** [AY2324S2-CS2103-F08-3/tp#50]
- Sort by:
  - [x] Name 
  - [x] Phone number
  - [x] Module
  - [x] Faculty :shipit:
  - [x] Venue
- [x] JUnit Testcases 
- [x] Update DG

**Comment by whitesnowx** [comment]
Can work towards map implementation for multiple attributes to sort in future iterations @whitesnowx
