### ISSUE TITLE
Update filter functionality for Availability

### ISSUE THREAD

**Issue by iynixil** [AY2324S2-CS2103-F08-3/tp#95]
- [ ] commands/FilterCommand.java
- [ ] parser/FilterCommandParser.java
- [ ] model/PersonHasAvailability.java (new)
- [ ] write JUnit tests

**Comment by whitesnowx** [comment]
Is this a duplicate for #118

**Comment by iynixil** [comment]
> Is this a duplicate for #118

oops yes, will close the duplicated one
